name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://les-gens-de-fourg.github.io/
          include-html: true

      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap" || echo "No changes"
          git push
